import { contextBridge, ipcRenderer } from 'electron';

contextBridge.exposeInMainWorld('gitRose', {
  openRepo: () => ipcRenderer.invoke('git:open-repo'),
  getCommits: (repoPath: string) => ipcRenderer.invoke('git:get-commits', repoPath),
  getGraph: (repoPath: string, ref?: string) => ipcRenderer.invoke('git:get-graph', repoPath, ref),
  getBranches: (repoPath: string) => ipcRenderer.invoke('git:get-branches', repoPath),
  getStatus: (repoPath: string) => ipcRenderer.invoke('git:get-status', repoPath),
  getDiff: (repoPath: string, filePath: string, staged: boolean) => ipcRenderer.invoke('git:get-diff', repoPath, filePath, staged),
  stageFile: (repoPath: string, filePath: string) => ipcRenderer.invoke('git:stage-file', repoPath, filePath),
  unstageFile: (repoPath: string, filePath: string) => ipcRenderer.invoke('git:unstage-file', repoPath, filePath),
  discardFile: (repoPath: string, filePath: string, isUntracked: boolean) => ipcRenderer.invoke('git:discard-file', repoPath, filePath, isUntracked),
  stageAll: (repoPath: string) => ipcRenderer.invoke('git:stage-all', repoPath),
  commit: (repoPath: string, message: string) => ipcRenderer.invoke('git:commit', repoPath, message),
  push: (repoPath: string) => ipcRenderer.invoke('git:push', repoPath),
  pull: (repoPath: string) => ipcRenderer.invoke('git:pull', repoPath),
  checkout: (repoPath: string, branch: string) => ipcRenderer.invoke('git:checkout', repoPath, branch),
  createBranch: (repoPath: string, branchName: string) => ipcRenderer.invoke('git:create-branch', repoPath, branchName),
  checkoutRemote: (repoPath: string, remoteBranch: string) => ipcRenderer.invoke('git:checkout-remote', repoPath, remoteBranch),
  getUser: (repoPath: string) => ipcRenderer.invoke('git:get-user', repoPath),
  stashList: (repoPath: string) => ipcRenderer.invoke('git:stash-list', repoPath),
  stashSave: (repoPath: string, message?: string) => ipcRenderer.invoke('git:stash-save', repoPath, message),
  stashApply: (repoPath: string, index: number) => ipcRenderer.invoke('git:stash-apply', repoPath, index),
  stashPop: (repoPath: string, index: number) => ipcRenderer.invoke('git:stash-pop', repoPath, index),
  stashDrop: (repoPath: string, index: number) => ipcRenderer.invoke('git:stash-drop', repoPath, index),
  runCommand: (repoPath: string, args: string[]) => ipcRenderer.invoke('git:run-command', repoPath, args),
  squashToCommit: (repoPath: string, hash: string, message: string) => ipcRenderer.invoke('git:squash-to-commit', repoPath, hash, message),
  rebase: (repoPath: string, branch: string) => ipcRenderer.invoke('git:rebase', repoPath, branch),
  cherryPick: (repoPath: string, hash: string) => ipcRenderer.invoke('git:cherry-pick', repoPath, hash),
  cherryPickToBranch: (repoPath: string, hash: string, branchName: string) => ipcRenderer.invoke('git:cherry-pick-to-branch', repoPath, hash, branchName),
});
